apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: davtrowebdbvault
  labels:
    app: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgui
    component: fastapi
    app.kubernetes.io/name: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgui
    app.kubernetes.io/instance: website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgui
    app.kubernetes.io/component: fastapi
data:
  APP_NAME: "website-db-vault-kaf-redis-arg-kust-kyv-gra-loki-temp-pgui"
  APP_ENV: "production"
  PYTHONUNBUFFERED: "1"
