apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
  namespace: davtrowebdbvault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - name: redis-insight
        image: redislabs/redisinsight:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  namespace: davtrowebdbvault
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: redis-insight
